BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "config" (
	"DBInitialised"	INTEGER NOT NULL DEFAULT 1,
	"StartTime"	TEXT NOT NULL DEFAULT '05:00',
	"StartCohortMins"	INTEGER NOT NULL DEFAULT 10,
	"ExtraCohorts"	INTEGER NOT NULL DEFAULT 3
);
CREATE TABLE IF NOT EXISTS "entrants" (
	"EntrantID"	INTEGER,
	"Bike"	TEXT,
	"BikeReg"	TEXT,
	"RiderName"	TEXT,
	"RiderFirst"	TEXT,
	"RiderLast"	TEXT,
	"RiderIBA"	TEXT,
	"PillionName"	TEXT,
	"PillionFirst"	TEXT,
	"PillionLast"	TEXT,
	"PillionIBA"	TEXT,
	"TeamID"	INTEGER NOT NULL DEFAULT 0,
	"Country"	TEXT DEFAULT 'UK',
	"OdoKms"	INTEGER NOT NULL DEFAULT 0,
	"OdoStart"	INTEGER,
	"OdoFinish"	INTEGER,
	"CorrectedMiles"	NUMERIC DEFAULT 0,
	"FinishTime"	TEXT,
	"StartTime"	TEXT,
	"EntrantStatus"	INTEGER NOT NULL DEFAULT 0,
	"Class"	INTEGER NOT NULL DEFAULT 0,
	"Phone"	TEXT,
	"Email"	TEXT,
	"NoKName"	TEXT,
	"NoKRelation"	TEXT,
	"NoKPhone"	TEXT,
	"Cohort"	INTEGER NOT NULL DEFAULT 0,
	"EntryDonation"	TEXT,
	"SquiresCheque"	TEXT,
	"SquiresCash"	TEXT,
	"RBLRAccount"	TEXT,
	"JustGivingAmt"	TEXT,
	"JustGivingURL"	TEXT,
	"Route"	TEXT,
	"RiderAddress"	TEXT,
	"PillionAddress"	TEXT,
	"PillionEmail"	TEXT,
	"PillionPhone"	TEXT,
	"RiderRBLR"	TEXT,
	"PillionRBLR"	TEXT,
	"Tshirt1"	INTEGER,
	"Tshirt2"	TEXT,
	"Patches"	INTEGER DEFAULT 0,
	"FreeCamping"	INTEGER DEFAULT 0,
	PRIMARY KEY("EntrantID")
);
COMMIT;
